version: '3.8'

services:
  chat-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chat-app
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5000}
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - .env
